### ISSUE TITLE
Config for meeting hour

### ISSUE THREAD

**Issue by MineKing9534** [SlimeCloud/SlimeBot#275]

**Comment by MineKing9534** [comment]
@MatitoDev Brauchen wir das eigentlich wirklich? Theoretisch sollte sich das ja nicht so oft ändern und dann kann man es ja manuell ändern (so wie du es ja jetzt auch gemacht hast)

**Comment by MatitoDev** [comment]
ja, muss dann halt trotzdem noch jemand im Code ändern
